### ISSUE TITLE
Hydration mismatch errors after upgrade to React 18

### ISSUE THREAD

**Issue by Qwal** [algolia/pwa-ecom-ui-template#51]
This is what I see after running the app with React 18:
![image](https://user-images.githubusercontent.com/685808/174771295-b4f4768e-861f-4fe1-b547-e1b46e8d167d.png)

It has impact on application ex. SEO & Performance will be downgraded if we do not match the SSR state with CSR state.

We are building POC around Algolia to validate if we can use it for new shop we are building and this is a first obstacle.

_Originally posted by @Qwal in https://github.com/algolia/instantsearch.js/issues/5243

**Comment by FabienMotte** [comment]
Hello @Qwal!

This should be fixed now, it was due to a dependency https://github.com/artsy/fresnel used for CSS media queries with SSR but this lib is not compatible with React 18 yet. Now, a basic `useMediaQuery` hook is used instead and all other dependencies have been updated.

Hope that helps, feel free to reopen if that's not the case.
